[package]
name = "csv_split"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv="1.1.6"
indicatif = "0.17.3"
rayon="1.5.1"